[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

### Update vanilla jimbos to be compatible with tiers

## BEGIN Baron
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = 'j_baron=            {order = 72,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "Baron",set = "Joker", config = {extra = 1.5}, pos = {x=6,y=12}},'
position = 'at'
payload = """
-- dogmod tiered baron
j_baron=            {order = 72,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "Baron",set = "Joker", config = {extra = {multmult = 1.5, canRankUp = true, tier = 1, maxTier = 2}}, pos = {x=6,y=12}},"""

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = """
if self.ability.name == 'Baron' and
    context.other_card:get_id() == 13 then
    if context.other_card.debuff then
        return {
            message = localize('k_debuffed'),
            colour = G.C.RED,
            card = self,
        }
    else
        return {
            x_mult = self.ability.extra,
            card = self
        }
    end
end
"""
position = 'at'
payload = """
if self.ability.name == 'Baron' and
    context.other_card:get_id() == 13 then
    if context.other_card.debuff then
        return {
            message = localize('k_debuffed'),
            colour = G.C.RED,
            card = self,
        }
    else
        return {
            x_mult = self.ability.extra.multmult,
            card = self
        }
    end
end
"""

### END Baron


### BEGIN Bloodstone

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = """j_bloodstone=       {order = 117,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 2, cost = 7, name = "Bloodstone", pos = {x=0,y=8}, set = "Joker", effect = "", config = {extra = {odds = 2, Xmult = 1.5}}, unlock_condition = {type = 'modify_deck', extra = {count = 30, suit = 'Hearts'}}},"""
position = 'at'
payload = """
-- dogmod tiered bloodstone
j_bloodstone=       {order = 117,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 2, cost = 7, name = "Bloodstone", pos = {x=0,y=8}, set = "Joker", effect = "", config = {extra = {canRankUp = true, tier = 1, maxTier = 2, odds = 2, Xmult = 1.5}}, unlock_condition = {type = 'modify_deck', extra = {count = 30, suit = 'Hearts'}}},"""

### Don't think we need to patch the scoring thing cus we just set the odds to be 1 in 1 and change the text


### END Bloodstone