[manifest]
version = "1.0.0"
dump_lua = true
priority = 1


### BEGIN Tiered Vanillas
### Update vanilla jimbos to be compatible with tiers
### Tier 1 = vanilla
### Effects:
### Baron: T2 = 2x mult for each king in hand
### Bloodstone: T2 = 100% chance of triggering

## BEGIN Baron
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = 'j_baron=            {order = 72,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "Baron",set = "Joker", config = {extra = 1.5}, pos = {x=6,y=12}},'
position = 'at'
payload = """
-- dogmod tiered baron
j_baron=            {order = 72,  unlocked = true, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 8, name = "Baron",set = "Joker", config = {extra = {multmult = 1.5, canRankUp = true, tier = 1, maxTier = 2}}, pos = {x=6,y=12}},"""

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = """
if self.ability.name == 'Baron' and
    context.other_card:get_id() == 13 then
    if context.other_card.debuff then
        return {
            message = localize('k_debuffed'),
            colour = G.C.RED,
            card = self,
        }
    else
        return {
            x_mult = self.ability.extra,
            card = self
        }
    end
end
"""
position = 'at'
payload = """
if self.ability.name == 'Baron' and
    context.other_card:get_id() == 13 then
    if context.other_card.debuff then
        return {
            message = localize('k_debuffed'),
            colour = G.C.RED,
            card = self,
        }
    else
        return {
            x_mult = self.ability.extra.multmult,
            card = self
        }
    end
end
"""

### END Baron


### BEGIN Bloodstone

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = """j_bloodstone=       {order = 117,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 2, cost = 7, name = "Bloodstone", pos = {x=0,y=8}, set = "Joker", effect = "", config = {extra = {odds = 2, Xmult = 1.5}}, unlock_condition = {type = 'modify_deck', extra = {count = 30, suit = 'Hearts'}}},"""
position = 'at'
payload = """
-- dogmod tiered bloodstone
j_bloodstone=       {order = 117,  unlocked = false, discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 2, cost = 7, name = "Bloodstone", pos = {x=0,y=8}, set = "Joker", effect = "", config = {extra = {canRankUp = true, tier = 1, maxTier = 2, odds = 2, Xmult = 1.5}}, unlock_condition = {type = 'modify_deck', extra = {count = 30, suit = 'Hearts'}}},"""

### Don't think we need to patch the scoring thing cus we just set the odds to be 1 in 1 and change the text


### END Bloodstone

### END Tiered Vanillas


### BEGIN Voucher Joker effect

#[[patches]]
#[patches.pattern]
#target = 'card.lua'
#match_indent = true
#pattern = """
#if self.ability.name == 'Stuntman' then
#    G.hand:change_size(-self.ability.extra.h_size)
#end
#"""
#position = 'after'
#payload = """
#if type(self.ability.extra) == 'table' and type(self.ability.extra.voucherSize) == 'number' then
#    G.shop_vouchers.config.card_limit = G.shop_vouchers.config.card_limit + self.ability.extra.voucherSize
#end
#"""
### END Voucher Joker effect


## BEGIN lucky effects patch
# patch lucky effects to account for Fixed Odds joker
[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = """
function Card:get_chip_mult()
    if self.debuff then return 0 end
    if self.ability.set == 'Joker' then return 0 end
    if self.ability.effect == "Lucky Card" then 
        if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then
            self.lucky_trigger = true
            return self.ability.mult
        else
            return 0
        end
    else  
        return self.ability.mult
    end
end
"""
position = 'at'
payload = """
function Card:get_chip_mult()
    if self.debuff then return 0 end
    if self.ability.set == 'Joker' then return 0 end
    if self.ability.effect == "Lucky Card" then
        local prob = 5
        if next(find_joker('j_dogmod_fixed_odds')) then
            prob = prob / (#find_joker('j_dogmod_fixed_odds') * 2)
        end 
        if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/prob then
            self.lucky_trigger = true
            return self.ability.mult
        else
            return 0
        end
    else  
        return self.ability.mult
    end
end
"""

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = """
if self.ability.p_dollars > 0 then
    if self.ability.effect == "Lucky Card" then 
        if pseudorandom('lucky_money') < G.GAME.probabilities.normal/15 then
            self.lucky_trigger = true
            ret = ret +  self.ability.p_dollars
        end
    else 
        ret = ret + self.ability.p_dollars
    end
end
"""
position = 'at'
payload = """
if self.ability.p_dollars > 0 then
    if self.ability.effect == "Lucky Card" then
        local prob = 15
        if next(find_joker('j_dogmod_fixed_odds')) then
            prob = prob / (#find_joker('j_dogmod_fixed_odds') * 2)
        end 
        print("probabilities", prob)
        if pseudorandom('lucky_money') < G.GAME.probabilities.normal/prob then
            self.lucky_trigger = true
            ret = ret +  self.ability.p_dollars
        end
    else 
        ret = ret + self.ability.p_dollars
    end
end
"""

### END lucky effects patch